version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgresslack
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user@123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
